### ISSUE TITLE
Feature Request: Support for Different Target Servers for Specific API Routes

### ISSUE THREAD

**Issue by jayxuz** [yisibell/h3-proxy#1]
I am currently using your package in my project. 
The package works well for proxying API requests.
 However, I have encountered a limitation that I believe could be a valuable addition to your package .

### Current Behavior:
The component successfully proxies API requests made to `/api`. All requests to the `/api` endpoint are forwarded to a single specified server.

### Desired Feature:
I would like the component to support routing requests to different servers based on the API route. Specifically, I want requests to `/api/xxx1` to be proxied to one server, while all other `/api` requests (except `/api/xxx1`) are proxied to a different server. This feature is crucial for my project as it involves interacting with multiple backend services.

### Example:
- Requests to `/api/xxx1` should be forwarded to `Server A` (Dev server).
- Requests to any other `/api` routes (like `/api/xxx2`, `/api/xxx3`, etc.) should be forwarded to `Server B` （Service Gateway）.

### Use Case:
This feature is particularly useful in a microservices architecture where different microservices are hosted on separate servers. It allows for more flexibility and control over the routing of API requests.

I believe this feature could benefit other users who might be in a similar situation. I am looking forward to your thoughts on this and would greatly appreciate it if this feature could be considered for implementation in a future release.

Thank you for your time and effort in maintaining this component.

**Comment by yisibell** [comment]
In fact, the current version is supported.

Pls see [Multiple proxy targets usage](https://github.com/yisibell/h3-proxy?tab=readme-ov-file#multiple-proxy-targets-usage)

[Or, using Array type options to define multiple proxy targets (added in v1.11.0)](https://github.com/yisibell/h3-proxy?tab=readme-ov-file#or-using-array-type-options-to-define-multiple-proxy-targets-added-in-v1110)
